import { randomUUID } from 'node:crypto';
import { expect, test } from '@playwright/test';

test('signs in once, restores before rendering, survives reload and clears expired identity', async ({ page, context }, testInfo) => {
  const email = `session-${randomUUID()}@example.test`;
  const password = 'a unique session passphrase';
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.clock.install();
  await page.goto('/register');
  await page.getByLabel('Display name', { exact: true }).fill('Session Browser');
  await page.getByLabel('Email address', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page).toHaveURL(/\/login\?registered=1$/);
  await page.getByLabel('Email address', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill('incorrect');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('alert')).toHaveText('Email or password is incorrect.');
  await expect(page.getByRole('alert')).toBeFocused();
  await page.getByLabel('Password', { exact: true }).fill(password);
  for (const width of [320, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeInViewport();
    if (width === 320 || width === 1440) await page.screenshot({ path: testInfo.outputPath(`login-${width}.png`), fullPage: true });
  }
  let releaseLogin!: () => void;
  let releaseSession!: () => void;
  const loginGate = new Promise<void>(resolve => { releaseLogin = resolve; });
  const sessionGate = new Promise<void>(resolve => { releaseSession = resolve; });
  let attempts = 0;
  let expiresAt = '';
  await page.route('**/api/auth/login', async route => {
    attempts++;
    await loginGate;
    // Capture expiry before Angular navigation can discard Chromium's response body.
    const response = await route.fetch({ maxRedirects: 0, maxRetries: 0 });
    expiresAt = (await response.json()).expiresAt;
    await route.fulfill({ response });
  });
  await page.route('**/api/auth/me', async route => { await sessionGate; await route.continue(); });
  const loggedIn = page.waitForResponse(response => response.url().endsWith('/api/auth/login') && response.status() === 200);
  await page.getByLabel('Password', { exact: true }).focus();
  await page.keyboard.press('Tab');
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('button', { name: 'Signing in…' })).toBeDisabled();
  await page.keyboard.press('Enter');
  releaseLogin();
  await loggedIn;
  await expect(page.getByText('Checking your session…', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Welcome, Session Browser' })).toHaveCount(0);
  releaseSession();
  await expect(page).toHaveURL(/\/workspace$/);
  await expect(page.getByRole('heading', { name: 'Welcome, Session Browser' })).toBeFocused();
  expect(attempts).toBe(1);
  expect((await context.cookies()).find(cookie => cookie.name === 'chat_session')?.httpOnly).toBe(true);
  expect(await page.evaluate(() => [document.cookie, localStorage.length, sessionStorage.length])).toEqual(['', 0, 0]);
  await page.unroute('**/api/auth/login');
  await page.unroute('**/api/auth/me');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Welcome, Session Browser' })).toBeVisible();
  await page.getByRole('link', { name: 'Overview', exact: true }).click();
  await page.getByRole('link', { name: 'Workspace', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Welcome, Session Browser' })).toBeVisible();
  const remaining = Date.parse(expiresAt) - await page.evaluate(() => Date.now());
  await page.clock.fastForward(Math.max(1, remaining));
  await expect(page).toHaveURL(/\/login\?reason=expired$/);
  await expect(page.getByText('Your session is missing or expired.', { exact: false })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Welcome, Session Browser' })).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('blocks anonymous access, distinguishes network failure and avoids redirect loops', async ({ page }) => {
  let checks = 0;
  page.on('request', request => { if (request.url().endsWith('/api/auth/me')) checks++; });
  await page.route('**/api/auth/me', route => route.fulfill({ status: 503, contentType: 'text/plain', body: 'private proxy detail' }), { times: 1 });
  await page.goto('/workspace');
  await expect(page).toHaveURL(/\/login\?reason=unavailable$/);
  await expect(page.getByText('We could not check your session.', { exact: false })).toBeVisible();
  await expect(page.locator('body')).not.toContainText('private proxy detail');
  expect(checks).toBe(1);
  await page.getByRole('link', { name: 'Try opening your workspace' }).click();
  await expect(page).toHaveURL(/\/login\?reason=required$/);
  await expect(page.getByText('Your session is missing or expired.', { exact: false })).toBeVisible();
  await expect(page.getByText('We could not check your session.', { exact: false })).toHaveCount(0);
  expect(checks).toBe(2);
  await expect(page.getByRole('heading', { name: /Welcome,/ })).toHaveCount(0);
});

test('logs out once, handles failure, rejects the old cookie and preserves another session', async ({ page, context, browser }, testInfo) => {
  const email = `logout-${randomUUID()}@example.test`;
  const password = 'a unique logout passphrase';
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/register');
  await page.getByLabel('Display name', { exact: true }).fill('Logout Browser');
  await page.getByLabel('Email address', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page).toHaveURL(/\/login\?registered=1$/);
  await page.getByLabel('Email address', { exact: true }).fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL(/\/workspace$/);
  const oldCookie = (await context.cookies()).find(cookie => cookie.name === 'chat_session')!;
  const other = await browser.newContext({ baseURL: testInfo.project.use.baseURL });
  try {
    const otherPage = await other.newPage();
    await otherPage.goto('/login');
    await otherPage.getByLabel('Email address', { exact: true }).fill(email);
    await otherPage.getByLabel('Password', { exact: true }).fill(password);
    await otherPage.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(otherPage).toHaveURL(/\/workspace$/);
    await page.route('**/api/auth/logout', route => route.fulfill({ status: 503, body: 'private detail' }), { times: 1 });
    await page.getByRole('button', { name: 'Sign out', exact: true }).click();
    await expect(page.getByRole('alert')).toHaveText('We could not confirm sign-out. Check your connection and try again.');
    await expect(page.getByRole('alert')).toBeFocused();
    await expect(page.getByRole('heading', { name: 'Welcome, Logout Browser' })).toBeVisible();
    for (const width of [320, 768, 1024, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeInViewport();
      if (width === 320 || width === 1440) await page.screenshot({ path: testInfo.outputPath(`logout-${width}.png`), fullPage: true });
    }
    let release!: () => void;
    const gate = new Promise<void>(resolve => { release = resolve; });
    let attempts = 0;
    await page.route('**/api/auth/logout', async route => { attempts++; await gate; await route.continue(); });
    await page.getByRole('button', { name: 'Sign out', exact: true }).focus();
    await page.keyboard.press('Enter');
    await expect(page.getByRole('button', { name: 'Signing out…' })).toBeDisabled();
    await page.keyboard.press('Enter');
    release();
    await expect(page).toHaveURL(/\/login\?reason=signed-out$/);
    await expect(page.getByText('You are signed out.', { exact: true })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Sign in', exact: true })).toBeFocused();
    expect(attempts).toBe(1);
    expect((await context.cookies()).some(cookie => cookie.name === 'chat_session')).toBe(false);
    expect(await page.evaluate(() => [document.cookie, localStorage.length, sessionStorage.length])).toEqual(['', 0, 0]);
    expect((await page.request.get('/api/auth/me', { headers: { cookie: `${oldCookie.name}=${oldCookie.value}` } })).status()).toBe(401);
    await page.reload();
    await page.getByRole('link', { name: 'Try opening your workspace' }).click();
    await expect(page).toHaveURL(/\/login\?reason=required$/);
    await expect(page.getByRole('heading', { name: 'Welcome, Logout Browser' })).toHaveCount(0);
    await otherPage.reload();
    await expect(otherPage.getByRole('heading', { name: 'Welcome, Logout Browser' })).toBeVisible();
    expect(errors).toEqual([]);
  } finally { await other.close(); }
});
